abbr -a -- 2f '2fa expensify | pbcopy'
abbr -a -- ad 'git add'
abbr -a -- adu 'git add -u'
abbr -a -- br 'git br'
abbr -a -- ci 'git ci'
abbr -a -- cia 'git ci -a'
abbr -a -- ciamen 'git ci --amend'
abbr -a -- co 'git co'
abbr -a -- cob 'git co -b'
abbr -a -- com 'git co main'
abbr -a -- cop 'git co .'
abbr -a -- dif 'git diff'
abbr -a -- e 'exa -la'
abbr -a -- et 'exa -laT'
abbr -a -- fet 'git fetch origin'
abbr -a -- gap 'git add --patch'
abbr -a -- gapl 'git apply'
abbr -a -- gcb git-clean-branches
abbr -a -- gco 'git co'
abbr -a -- gdc 'git diff --cached'
abbr -a -- gifconvert 'ffmpeg -i input.mov -f gif -filter_complex "[0:v] fps=24,scale=w=1500:h=-1,split [a][b];[a] palettegen [p];[b][p] paletteuse" output.gif'
abbr -a -- gl 'git log'
abbr -a -- gpo 'git pull origin'
abbr -a -- gpom 'git pull origin main'
abbr -a -- gr 'cd (git rev-parse --show-toplevel)'
abbr -a -- gw 'grunt; and grunt watch'
abbr -a -- iosSim /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator
abbr -a -- it git
abbr -a -- jop 'j; and pbpaste'
abbr -a -- jp jsonPretty
abbr -a -- na 'npm run android'
abbr -a -- nd 'npm run desktop'
abbr -a -- ni 'npm run ios'
abbr -a -- nin 'npm i'
abbr -a -- nw 'npm run web'
abbr -a -- pin 'pod install'
abbr -a -- puf 'git push -f origin'
abbr -a -- rbm 'git rebase main'
abbr -a -- recommit 'git ci --amend --no-edit'
abbr -a -- rgf 'rg -F'
abbr -a -- rgfi 'rg -Fi'
abbr -a -- rgi 'rg -i'
abbr -a -- rrm 'rm -rf'
abbr -a -- st 'git st'
abbr -a -- stt 'git stash'
abbr -a -- utc 'date -u +"%Y-%m-%dT%H:%M:%SZ"'
abbr -a -- vag vagrant
abbr -a -- venv 'source venv/bin/activate.fish'
abbr -a --set-cursor='%' -- cim 'git commit -m "%"'
abbr -a --set-cursor='%' -- ciam 'git commit -am "%"'
abbr -a --function abbr_pu -- pu
abbr -a --set-cursor='%' -- rrg 'rg -Fi "%" ./*'
