abbr -a -U -- 2f '2fa expensify | pbcopy'
abbr -a -U -- ad 'git add'
abbr -a -U -- adu 'git add -u'
abbr -a -U -- br 'git br'
abbr -a -U -- ci 'git ci'
abbr -a -U -- ciam 'git ci -am'
abbr -a -U -- ciamen 'git ci --amend'
abbr -a -U -- cim 'git ci -m'
abbr -a -U -- co 'git co'
abbr -a -U -- cob 'git co -b'
abbr -a -U -- com 'git co master'
abbr -a -U -- cop 'git co .'
abbr -a -U -- dif 'git diff'
abbr -a -U -- e 'exa -la'
abbr -a -U -- fet 'git fetch origin'
abbr -a -U -- fpu 'git push -f origin'
abbr -a -U -- gap 'git add --patch'
abbr -a -U -- gcb git-clean-branches
abbr -a -U -- gco 'git co'
abbr -a -U -- gdc 'git diff --cached'
abbr -a -U -- gifconvert 'ffmpeg -i input.mov -f gif -filter_complex "[0:v] fps=24,scale=w=1500:h=-1,split [a][b];[a] palettegen [p];[b][p] paletteuse" output.gif'
abbr -a -U -- gl 'git log'
abbr -a -U -- gpom 'git pull origin master'
abbr -a -U -- it git
abbr -a -U -- jp jsonPretty
abbr -a -U -- pu 'git push origin'
abbr -a -U -- puf 'git push -f origin'
abbr -a -U -- scpb scp\ -o\ \'ProxyJump\ bastion\'
abbr -a -U -- st 'git st'
abbr -a -U -- utc 'date -u +"%Y-%m-%dT%H:%M:%SZ"'
abbr -a -U -- venv 'source venv/bin/activate.fish'
